name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install browsers
      run: pwsh bin/Debug/net6.0/playwright.ps1 install ${{ matrix.browser }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -- Playwright.BrowserName=${{ matrix.browser }}
